
version: '3.8'

services:
  ai-assistant-server:
    build: .
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Опционально: можно добавить базу данных
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
